import type { Metadata } from "next";
import "@/app/globals.css";
import Hero from "@/app/components/dynamic-course/Hero";
import SideBar from "@/app/components/dynamic-course/SideBar";
import Heading from "@/app/components/dynamic-course/Heading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { courseId: string; contentId: string };
}) {
  return (
    <main>
      {/* hero section that has details of the course */}
      <Hero />

      {/* heading that controls sidebar toggle */}
      <section className="md:px-10 px-5">
        <Heading />
      </section>

      {/* section with course content */}
      <section className="xl:flex">
        {/* sidebar to navigate between sub-courses */}
        <SideBar id={params.courseId} />

        {/* course content like video */}
        {children}
      </section>
    </main>
  );
}
