import type { Metadata } from "next";
import "@/app/globals.css";
import Hero from "@/app/components/dynamic-course/Hero";
import SideBar from "@/app/components/dynamic-course/SideBar";
import Heading from "@/app/components/dynamic-course/Heading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { courseId: string; contentId: string };
}) {
  return (
    <html lang="en">
      <body>
        <main className="scroll">
          <Hero />

          <section className="md:px-10 px-5">
            <Heading />
          </section>

          <section className="xl:flex">
            <SideBar id={params.courseId} />

            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
